drop table T_YSB_WEIXINORDER;
create table T_YSB_WEIXINORDER
(
	[FSHOPPINGCARTID] [int] IDENTITY(1,1) NOT NULL,
	[FBILLNO] varchar(30) NOT NULL DEFAULT ' ',
);

drop table T_YSB_WEIXINORDERENTRY;
create table T_YSB_WEIXINORDERENTRY
(
	[FSHOPPINGCARTENTRYID] [int] IDENTITY(1,1) NOT NULL,
	[FSHOPPINGCARTID] [int] NOT NULL DEFAULT 0,
	[FPRODUCTID] [int] NOT NULL DEFAULT 0,--产品
	[FSTUDENTID] [int] NOT NULL DEFAULT 0,--学生 
	[FAuxPropId] [int] NOT NULL DEFAULT 0,--辅助属性
	[FCOUNT] [int] NOT NULL DEFAULT 0,--个数
	CONSTRAINT [PK_dbo.PK_YSB_WEIXINORDERENTRY] PRIMARY KEY CLUSTERED 
	(
		[FSHOPPINGCARTENTRYID] ASC
	)
) ;

drop table T_YSB_WEIXINORDERENTRY_L;
create table T_YSB_WEIXINORDERENTRY_L
(
	[FPKID] [int] IDENTITY(1,1) NOT NULL,
	[FLOCALEID] [int] NOT NULL DEFAULT 0,
	[FSHOPPINGCARTENTRYID] [int] NOT NULL DEFAULT 0,
	[FNAME] [nchar](255) NOT NULL DEFAULT ' ',--姓名
	CONSTRAINT [PK_dbo.PK_YSB_WEIXINORDERENTRY_L] PRIMARY KEY CLUSTERED 
	(
		[FPKID] ASC
	)
);
