drop table T_YSB_SHOPPINGCART;
create table T_YSB_SHOPPINGCART
(
	[FSHOPPINGCARTID] [int] IDENTITY(1,1) NOT NULL,
	[FPRODUCTID] [int] NOT NULL DEFAULT 0,--产品
	[FSTUDENTID] [int] NOT NULL DEFAULT 0,--学生 
	[FAuxPropId] [int] NOT NULL DEFAULT 0,--辅助属性
	[FCOUNT] [int] NOT NULL DEFAULT 0,--个数
	CONSTRAINT [PK_dbo.PK_YSB_SHOPPINGCART] PRIMARY KEY CLUSTERED 
	(
		[FSHOPPINGCARTID] ASC
	)
) ;

drop table T_YSB_SHOPPINGCART_L;
create table T_YSB_SHOPPINGCART_L
(
	[FPKID] [int] IDENTITY(1,1) NOT NULL,
	[FLOCALEID] [int] NOT NULL DEFAULT 0,
	[FSHOPPINGCARTID] [int] NOT NULL DEFAULT 0,
	[FNAME] [nchar](255) NOT NULL DEFAULT ' ',--姓名
	CONSTRAINT [PK_dbo.PK_YSB_SHOPPINGCART_L] PRIMARY KEY CLUSTERED 
	(
		[FPKID] ASC
	)
);
